### ISSUE TITLE
Bootstrap classes collision

### ISSUE THREAD

**Issue by BlazeIsClone** [Tetrag11/Wordpress-test-1#2]
Unsafe code :

![image](https://user-images.githubusercontent.com/64116737/161064141-5bf23456-02bf-4e4e-a23d-60d0936cfe80.png)

Safe code : 

```html
<div class="col-md-6">
       <div class="custom-col"></div>
</div>
```

```css
.custom-col {
justify-self: center;
}
```
